apiVersion: 1
datasources:
  - uid: "5d7bb398-3416-4ee5-9adf-c045d7577c48"
    name: "IMEdge Datasource"
    type: "yesoreyeram-infinity-datasource"
    url: "https://monitoring.example.com/icingaweb2/imedge/grafana"
    basicAuth: false
    isDefault: false
    jsonData:
      allowedHosts:
        - "https://monitoring.example.com"
      auth_method: "bearerToken"
      global_queries: []
      httpHeaderName1: "Accept"
      oauthPassThru: false
      pdcInjected: false
    readOnly: false
    secureJsonData:
      bearerToken: "0c1e2669-31af-471d-bdef-b3932e29e1bf"
      httpHeaderValue1: "application/json"
